"""
This type stub file was generated by pyright.
"""
from enum import Enum
from typing import Tuple, Union
from numpy.typing import NDArray

__all__ = ["DsetType", "Strappy", "Data"]


class MemoryView:  # Note: Supports buffer protocol.
    base: "Array"
    size: int
    itemsize: int
    nbytes: int
    ndim: int
    shape: Tuple[int, ...]
    strides: Tuple[int, ...]
    suboffsets: Tuple[int, ...]
    T: "MemoryView"

    def copy(self) -> "MemoryView": ...
    def copy_fortran(self) -> "MemoryView": ...
    def is_c_contig(self) -> bool: ...
    def is_f_contig(self) -> bool: ...


class Array:
    memview: MemoryView


class DsetType(int, Enum):
    pass


class Data:
    pass


class Strappy:
    def __init__(self, data: Data) -> None: ...
    def compress_col(self, data) -> MemoryView: ...
    def compress_numpy(self, arr: NDArray) -> MemoryView: ...
    def compress(self, MemoryView) -> MemoryView: ...
    def compress_to_internal_buf(self, data: Union[bytes, memoryview, Array]) -> Array: ...
